function draw_enemy() {
	
}

var enemy = {
	"0": {
		"name": "Slime",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"1": {
		"name": "Red Slime",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"2": {
		"name": "Drakee",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"3": {
		"name": "Ghost",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"4": {
		"name": "Magician",
		"id": "4",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"5": {
		"name": "Magidrakee",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"6": {
		"name": "Scorpion",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"7": {
		"name": "Druin",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"8": {
		"name": "Poltergeist",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"9": {
		"name": "Droll",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"10": {
		"name": "Drakeema",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"11": {
		"name": "Skeleton",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"12": {
		"name": "Warlock",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"13": {
		"name": "Metal Scorpion",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"14": {
		"name": "Wolf",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"15": {
		"name": "Wraith",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"16": {
		"name": "Metal Slime",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"17": {
		"name": "Specter",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"18": {
		"name": "Wolflord",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"19": {
		"name": "Druinlord",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"20": {
		"name": "Drollmagi",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"21": {
		"name": "Wyvern",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"22": {
		"name": "Rogue Scorpion",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"23": {
		"name": "Wraith Knight",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"24": {
		"name": "Golem",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"25": {
		"name": "Goldman",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"26": {
		"name": "Knight",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"27": {
		"name": "Magiwyvern",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"28": {
		"name": "Demon Knight",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"29": {
		"name": "Werewolf",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"30": {
		"name": "Green Dragon",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"31": {
		"name": "Starwyvern",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"32": {
		"name": "Wizard",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"33": {
		"name": "Axe Knight",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"34": {
		"name": "Blue Dragon",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"35": {
		"name": "Stoneman",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"36": {
		"name": "Armored Knight",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"37": {
		"name": "Red Dragon",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"38": {
		"name": "Dragonlord",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	},
	"39": {
		"name": "Dragonlord",
		"strength": "",
		"agility": "",
		"hp": "",
		"sleep_resist": "",
		"stopspell_resist": "",
		"hurt_resist": "",
		"dodge": "",
		"experience": "",
		"gold": ""
	}
};