export default {
    screenTilesWide: 25,
    screenTileHigh: 15,
    offsetX: 12,
    offsetY: 6,
    tileWidth: 32,
    tileHeight: 32,
    fontWidth: 16,
    fontHeight: 16,
    movementSpeed: 12,
    sprites: {
        battle: 'assets/sprites/battle.png',
        characters: 'assets/sprites/characters.png',
        enemies: 'assets/sprites/monsters.png',
        font: 'assets/sprites/font.png',
        menu: 'assets/sprites/menu.png',
        tiles: 'assets/sprites/tiles.png',
        title: 'assets/sprites/title.png',
    },
};
